version: '3.9'

services:
  proxy:
    image: tivix/docker-nginx:v17
    restart: unless-stopped
    depends_on:
      - frontend
    ports:
      - "8080:80"
    environment:
      - UPSTREAMS=/:frontend:3000
      
  frontend:
    restart: unless-stopped
    stdin_open: true
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend/src:/code/src
      - ./frontend/public:/code/public
    ports:
      - '3000:3000'